import { IChingHexagram } from '@/types';

export const HEXAGRAMS_64: Omit<IChingHexagram, 'lines'>[] = [
  { number: 1, name: '乾', nameEn: 'The Creative', upperTrigram: '乾', lowerTrigram: '乾', judgment: '元亨利貞。', image: '天行健，君子以自強不息。' },
  { number: 2, name: '坤', nameEn: 'The Receptive', upperTrigram: '坤', lowerTrigram: '坤', judgment: '元亨，利牝馬之貞。', image: '地勢坤，君子以厚德載物。' },
  { number: 3, name: '屯', nameEn: 'Difficulty', upperTrigram: '坎', lowerTrigram: '震', judgment: '元亨利貞，勿用有攸往，利建侯。', image: '雲雷屯，君子以經綸。' },
  { number: 4, name: '蒙', nameEn: 'Youthful Folly', upperTrigram: '艮', lowerTrigram: '坎', judgment: '亨。匪我求童蒙，童蒙求我。', image: '山下出泉，蒙。君子以果行育德。' },
  { number: 5, name: '需', nameEn: 'Waiting', upperTrigram: '坎', lowerTrigram: '乾', judgment: '有孚，光亨，貞吉，利涉大川。', image: '雲上於天，需。君子以飲食宴樂。' },
  { number: 6, name: '訟', nameEn: 'Conflict', upperTrigram: '乾', lowerTrigram: '坎', judgment: '有孚窒惕，中吉，終凶。', image: '天與水違行，訟。君子以作事謀始。' },
  { number: 7, name: '師', nameEn: 'The Army', upperTrigram: '坤', lowerTrigram: '坎', judgment: '貞，丈人吉，無咎。', image: '地中有水，師。君子以容民畜眾。' },
  { number: 8, name: '比', nameEn: 'Union', upperTrigram: '坎', lowerTrigram: '坤', judgment: '吉。原筮元永貞，無咎。', image: '地上有水，比。先王以建萬國，親諸侯。' },
  { number: 9, name: '小畜', nameEn: 'Small Taming', upperTrigram: '巽', lowerTrigram: '乾', judgment: '亨。密雲不雨，自我西郊。', image: '風行天上，小畜。君子以懿文德。' },
  { number: 10, name: '履', nameEn: 'Treading', upperTrigram: '乾', lowerTrigram: '兌', judgment: '履虎尾，不咥人，亨。', image: '上天下澤，履。君子以辨上下，定民志。' },
  { number: 11, name: '泰', nameEn: 'Peace', upperTrigram: '坤', lowerTrigram: '乾', judgment: '小往大來，吉亨。', image: '天地交，泰。后以財成天地之道。' },
  { number: 12, name: '否', nameEn: 'Standstill', upperTrigram: '乾', lowerTrigram: '坤', judgment: '否之匪人，不利君子貞。', image: '天地不交，否。君子以儉德辟難。' },
  { number: 13, name: '同人', nameEn: 'Fellowship', upperTrigram: '乾', lowerTrigram: '離', judgment: '同人于野，亨。', image: '天與火，同人。君子以類族辨物。' },
  { number: 14, name: '大有', nameEn: 'Great Possession', upperTrigram: '離', lowerTrigram: '乾', judgment: '元亨。', image: '火在天上，大有。君子以遏惡揚善。' },
  { number: 15, name: '謙', nameEn: 'Modesty', upperTrigram: '坤', lowerTrigram: '艮', judgment: '亨，君子有終。', image: '地中有山，謙。君子以裒多益寡。' },
  { number: 16, name: '豫', nameEn: 'Enthusiasm', upperTrigram: '震', lowerTrigram: '坤', judgment: '利建侯行師。', image: '雷出地奮，豫。君子以作樂崇德。' },
  { number: 17, name: '隨', nameEn: 'Following', upperTrigram: '兌', lowerTrigram: '震', judgment: '元亨利貞，無咎。', image: '澤中有雷，隨。君子以嚮晦入宴息。' },
  { number: 18, name: '蠱', nameEn: 'Decay', upperTrigram: '艮', lowerTrigram: '巽', judgment: '元亨，利涉大川。', image: '山下有風，蠱。君子以振民育德。' },
  { number: 19, name: '臨', nameEn: 'Approach', upperTrigram: '坤', lowerTrigram: '兌', judgment: '元亨利貞。至于八月有凶。', image: '澤上有地，臨。君子以教思無窮。' },
  { number: 20, name: '觀', nameEn: 'Contemplation', upperTrigram: '巽', lowerTrigram: '坤', judgment: '盥而不薦，有孚顒若。', image: '風行地上，觀。君子以省方觀民設教。' },
  { number: 21, name: '噬嗑', nameEn: 'Biting Through', upperTrigram: '離', lowerTrigram: '震', judgment: '亨。利用獄。', image: '雷電噬嗑，先王以明罰敕法。' },
  { number: 22, name: '賁', nameEn: 'Grace', upperTrigram: '艮', lowerTrigram: '離', judgment: '亨。小利有攸往。', image: '山下有火，賁。君子以明庶政。' },
  { number: 23, name: '剝', nameEn: 'Splitting Apart', upperTrigram: '艮', lowerTrigram: '坤', judgment: '不利有攸往。', image: '山附於地，剝。君子以厚下安宅。' },
  { number: 24, name: '復', nameEn: 'Return', upperTrigram: '坤', lowerTrigram: '震', judgment: '亨。出入無疾，朋來無咎。', image: '雷在地中，復。先王以至日閉關。' },
  { number: 25, name: '無妄', nameEn: 'Innocence', upperTrigram: '乾', lowerTrigram: '震', judgment: '元亨利貞。其匪正有眚。', image: '天下雷行，無妄。君子以茂對時育萬物。' },
  { number: 26, name: '大畜', nameEn: 'Great Taming', upperTrigram: '艮', lowerTrigram: '乾', judgment: '利貞，不家食吉，利涉大川。', image: '天在山中，大畜。君子以多識前言往行。' },
  { number: 27, name: '頤', nameEn: 'Mouth Corners', upperTrigram: '艮', lowerTrigram: '震', judgment: '貞吉。觀頤，自求口實。', image: '山下有雷，頤。君子以慎言語，節飲食。' },
  { number: 28, name: '大過', nameEn: 'Great Exceeding', upperTrigram: '兌', lowerTrigram: '巽', judgment: '棟橈，利有攸往，亨。', image: '澤滅木，大過。君子以獨立不懼，遯世無悶。' },
  { number: 29, name: '坎', nameEn: 'The Abysmal', upperTrigram: '坎', lowerTrigram: '坎', judgment: '習坎，有孚，維心亨。', image: '水洊至，習坎。君子以常德行。' },
  { number: 30, name: '離', nameEn: 'The Clinging', upperTrigram: '離', lowerTrigram: '離', judgment: '利貞，亨。畜牝牛，吉。', image: '明兩作，離。大人以繼明照於四方。' },
  { number: 31, name: '咸', nameEn: 'Influence', upperTrigram: '兌', lowerTrigram: '艮', judgment: '亨，利貞，取女吉。', image: '山上有澤，咸。君子以虛受人。' },
  { number: 32, name: '恆', nameEn: 'Duration', upperTrigram: '震', lowerTrigram: '巽', judgment: '亨，無咎，利貞，利有攸往。', image: '雷風，恆。君子以立不易方。' },
  { number: 33, name: '遯', nameEn: 'Retreat', upperTrigram: '乾', lowerTrigram: '艮', judgment: '亨，小利貞。', image: '天下有山，遯。君子以遠小人。' },
  { number: 34, name: '大壯', nameEn: 'Great Power', upperTrigram: '震', lowerTrigram: '乾', judgment: '利貞。', image: '雷在天上，大壯。君子以非禮弗履。' },
  { number: 35, name: '晉', nameEn: 'Progress', upperTrigram: '離', lowerTrigram: '坤', judgment: '康侯用錫馬蕃庶，晝日三接。', image: '明出地上，晉。君子以自昭明德。' },
  { number: 36, name: '明夷', nameEn: 'Darkening', upperTrigram: '坤', lowerTrigram: '離', judgment: '利艱貞。', image: '明入地中，明夷。君子以蒞眾。' },
  { number: 37, name: '家人', nameEn: 'The Family', upperTrigram: '巽', lowerTrigram: '離', judgment: '利女貞。', image: '風自火出，家人。君子以言有物。' },
  { number: 38, name: '睽', nameEn: 'Opposition', upperTrigram: '離', lowerTrigram: '兌', judgment: '小事吉。', image: '上火下澤，睽。君子以同而異。' },
  { number: 39, name: '蹇', nameEn: 'Obstruction', upperTrigram: '坎', lowerTrigram: '艮', judgment: '利西南，不利東北。', image: '山上有水，蹇。君子以反身修德。' },
  { number: 40, name: '解', nameEn: 'Deliverance', upperTrigram: '震', lowerTrigram: '坎', judgment: '利西南，無所往，其來復吉。', image: '雷雨作，解。君子以赦過宥罪。' },
  { number: 41, name: '損', nameEn: 'Decrease', upperTrigram: '艮', lowerTrigram: '兌', judgment: '有孚，元吉，無咎，可貞。', image: '山下有澤，損。君子以懲忿窒欲。' },
  { number: 42, name: '益', nameEn: 'Increase', upperTrigram: '巽', lowerTrigram: '震', judgment: '利有攸往，利涉大川。', image: '風雷，益。君子以見善則遷。' },
  { number: 43, name: '夬', nameEn: 'Breakthrough', upperTrigram: '兌', lowerTrigram: '乾', judgment: '揚于王庭，孚號有厲。', image: '澤上于天，夬。君子以施祿及下。' },
  { number: 44, name: '姤', nameEn: 'Coming to Meet', upperTrigram: '乾', lowerTrigram: '巽', judgment: '女壯，勿用取女。', image: '天下有風，姤。君子以施命誥四方。' },
  { number: 45, name: '萃', nameEn: 'Gathering', upperTrigram: '兌', lowerTrigram: '坤', judgment: '亨。王假有廟，利見大人。', image: '澤上于地，萃。君子以除戎器。' },
  { number: 46, name: '升', nameEn: 'Pushing Upward', upperTrigram: '坤', lowerTrigram: '巽', judgment: '元亨，用見大人，勿恤。', image: '地中生木，升。君子以順德。' },
  { number: 47, name: '困', nameEn: 'Oppression', upperTrigram: '兌', lowerTrigram: '坎', judgment: '亨，貞，大人吉，無咎。', image: '澤無水，困。君子以致命遂志。' },
  { number: 48, name: '井', nameEn: 'The Well', upperTrigram: '坎', lowerTrigram: '巽', judgment: '改邑不改井，無喪無得。', image: '木上有水，井。君子以勞民勸相。' },
  { number: 49, name: '革', nameEn: 'Revolution', upperTrigram: '兌', lowerTrigram: '離', judgment: '己日乃孚，元亨利貞，悔亡。', image: '澤中有火，革。君子以治歷明時。' },
  { number: 50, name: '鼎', nameEn: 'The Cauldron', upperTrigram: '離', lowerTrigram: '巽', judgment: '元吉，亨。', image: '木上有火，鼎。君子以正位凝命。' },
  { number: 51, name: '震', nameEn: 'The Arousing', upperTrigram: '震', lowerTrigram: '震', judgment: '亨。震來虩虩，笑言啞啞。', image: '洊雷，震。君子以恐懼修省。' },
  { number: 52, name: '艮', nameEn: 'Keeping Still', upperTrigram: '艮', lowerTrigram: '艮', judgment: '艮其背，不獲其身。', image: '兼山，艮。君子以思不出其位。' },
  { number: 53, name: '漸', nameEn: 'Development', upperTrigram: '巽', lowerTrigram: '艮', judgment: '女歸吉，利貞。', image: '山上有木，漸。君子以居賢德善俗。' },
  { number: 54, name: '歸妹', nameEn: 'Marrying Maiden', upperTrigram: '震', lowerTrigram: '兌', judgment: '征凶，無攸利。', image: '澤上有雷，歸妹。君子以永終知敝。' },
  { number: 55, name: '豐', nameEn: 'Abundance', upperTrigram: '震', lowerTrigram: '離', judgment: '亨，王假之，勿憂。', image: '雷電皆至，豐。君子以折獄致刑。' },
  { number: 56, name: '旅', nameEn: 'The Wanderer', upperTrigram: '離', lowerTrigram: '艮', judgment: '小亨，旅貞吉。', image: '山上有火，旅。君子以明慎用刑。' },
  { number: 57, name: '巽', nameEn: 'The Gentle', upperTrigram: '巽', lowerTrigram: '巽', judgment: '小亨，利有攸往，利見大人。', image: '隨風，巽。君子以申命行事。' },
  { number: 58, name: '兌', nameEn: 'The Joyous', upperTrigram: '兌', lowerTrigram: '兌', judgment: '亨，利貞。', image: '麗澤，兌。君子以朋友講習。' },
  { number: 59, name: '渙', nameEn: 'Dispersion', upperTrigram: '巽', lowerTrigram: '坎', judgment: '亨。王假有廟，利涉大川。', image: '風行水上，渙。君子以享于帝。' },
  { number: 60, name: '節', nameEn: 'Limitation', upperTrigram: '坎', lowerTrigram: '兌', judgment: '亨。苦節不可貞。', image: '澤上有水，節。君子以制數度。' },
  { number: 61, name: '中孚', nameEn: 'Inner Truth', upperTrigram: '巽', lowerTrigram: '兌', judgment: '豚魚吉，利涉大川，利貞。', image: '澤上有風，中孚。君子以議獄緩死。' },
  { number: 62, name: '小過', nameEn: 'Small Exceeding', upperTrigram: '震', lowerTrigram: '艮', judgment: '亨，利貞，可小事，不可大事。', image: '山上有雷，小過。君子以行過乎恭。' },
  { number: 63, name: '既濟', nameEn: 'After Completion', upperTrigram: '坎', lowerTrigram: '離', judgment: '亨，小利貞，初吉終亂。', image: '水在火上，既濟。君子以思患而豫防之。' },
  { number: 64, name: '未濟', nameEn: 'Before Completion', upperTrigram: '離', lowerTrigram: '坎', judgment: '亨，小狐汔濟，濡其尾，無攸利。', image: '火在水上，未濟。君子以慎辨物居方。' },
];
